(()=>{
const products=window.JF_PRODUCTS||[];let category='lancamentos',query='',sort='featured',selected=null,selectedSize='M';
const favs=new Set(JSON.parse(localStorage.getItem('jf-favs')||'[]'));const cart=JSON.parse(localStorage.getItem('jf-cart')||'[]');
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],money=n=>n==null?'Preço em breve':'$'+n.toFixed(2);
const catName=c=>({lancamentos:'Lançamentos',feminino:'Feminino',oversized:'Oversized',masculino:'Masculino',infantil:'Infantil'}[c]||c);
function persist(){localStorage.setItem('jf-favs',JSON.stringify([...favs]));localStorage.setItem('jf-cart',JSON.stringify(cart));updateBadges()}
function cartTotal(){return cart.reduce((sum,x)=>{const p=products.find(z=>z.slug===x.slug);return sum+(p?.price||0)*x.qty},0)}
function list(){let a=products.filter(p=>category==='lancamentos'?p.newArrival:p.category===category);if(query)a=a.filter(p=>(p.title+' '+p.subcategory+' '+p.description).toLowerCase().includes(query));if(sort==='az')a.sort((x,y)=>x.title.localeCompare(y.title));else if(sort==='low')a.sort((x,y)=>(x.price??9999)-(y.price??9999));else if(sort==='high')a.sort((x,y)=>(y.price??-1)-(x.price??-1));else a.sort((x,y)=>(y.featured?1:0)-(x.featured?1:0));return a}
function render(){const a=list();$('#productCount').textContent=a.length+' produtos';$('#emptyState').hidden=a.length>0;$('#productGrid').innerHTML=a.map(p=>`<article class="product-card"><div class="product-image" data-open="${p.slug}"><img src="${p.images[0]||''}" alt="${p.title}" loading="lazy">${p.newArrival?'<span class="new-tag">NOVO</span>':''}</div><button class="heart ${favs.has(p.slug)?'active':''}" data-fav="${p.slug}" aria-label="Favoritar">${favs.has(p.slug)?'♥':'♡'}</button><div class="product-meta"><div class="product-category">${p.subcategory}</div><div class="product-name" data-open="${p.slug}">${p.title}</div><div class="product-price ${p.price==null?'pending':''}">${money(p.price)}</div></div></article>`).join('');$$('[data-open]').forEach(x=>x.onclick=()=>openProduct(x.dataset.open));$$('[data-fav]').forEach(x=>x.onclick=e=>{e.stopPropagation();toggleFav(x.dataset.fav)})}
function setCategory(c){category=c;query='';$('#searchInput').value='';$('#pageTitle').textContent=catName(c);$('#crumbCurrent').textContent=catName(c);$$('.nav-link').forEach(n=>n.classList.toggle('active',n.dataset.category===c));$('#mainNav').classList.remove('open');render();window.scrollTo({top:0,behavior:'smooth'})}
function toggleFav(slug){favs.has(slug)?favs.delete(slug):favs.add(slug);persist();render();renderFavorites()}
function updateBadges(){$('#favBadge').textContent=favs.size;$('#cartBadge').textContent=cart.reduce((s,x)=>s+x.qty,0)}
function openDrawer(el){$('#drawerBackdrop').hidden=false;el.classList.add('open');el.setAttribute('aria-hidden','false')}function closeDrawers(){$$('.drawer').forEach(d=>{d.classList.remove('open');d.setAttribute('aria-hidden','true')});$('#drawerBackdrop').hidden=true}
function openProduct(slug){selected=products.find(p=>p.slug===slug);if(!selected)return;selectedSize='M';const sizes=selected.category==='infantil'?['2','4','6','8','10','12']:selected.category==='oversized'?['S','M','L','XL','2XL']:['S','M','L','XL'];$('#productDetail').innerHTML=`<div class="product-detail-grid"><div><div class="detail-image"><img src="${selected.images[0]||''}" alt="${selected.title}"></div></div><div><div class="detail-category">${selected.subcategory}</div><h2 class="detail-title">${selected.title}</h2><div class="detail-price">${money(selected.price)}</div><p class="detail-desc">${selected.description||'Peça cristã com acabamento premium e estampa de alta durabilidade.'}</p><p class="detail-desc"><strong>Entrega em qualquer lugar dos Estados Unidos.</strong><br>Não existe pedido mínimo.</p><label class="option-label">Tamanho</label><div class="size-row">${sizes.map(s=>`<button class="size-btn ${s==='M'?'active':''}" data-size="${s}">${s}</button>`).join('')}</div><div class="detail-actions"><button class="primary" id="addCartDetail" ${selected.price==null?'disabled':''}>ADICIONAR À SACOLA</button><button class="secondary" id="favDetail">${favs.has(selected.slug)?'♥ FAVORITO':'♡ FAVORITAR'}</button></div>${selected.price==null?'<p class="checkout-note">Preço ainda não definido para esta categoria.</p>':''}</div></div>`;$$('[data-size]').forEach(b=>b.onclick=()=>{selectedSize=b.dataset.size;$$('[data-size]').forEach(x=>x.classList.toggle('active',x===b))});$('#favDetail').onclick=()=>{toggleFav(selected.slug);$('#favDetail').textContent=favs.has(selected.slug)?'♥ FAVORITO':'♡ FAVORITAR'};const add=$('#addCartDetail');if(add)add.onclick=()=>addCart(selected,selectedSize);openDrawer($('#productDrawer'))}
function addCart(p,size){if(p.price==null)return;const found=cart.find(x=>x.slug===p.slug&&x.size===size);found?found.qty++:cart.push({slug:p.slug,size,qty:1});persist();renderCart();closeDrawers();openDrawer($('#cartDrawer'))}
function renderCart(){if(!cart.length){$('#cartItems').innerHTML='<p class="checkout-note">Sua sacola está vazia.</p>';$('#cartTotal').textContent='$0.00';return}$('#cartItems').innerHTML=cart.map((x,i)=>{const p=products.find(z=>z.slug===x.slug);if(!p)return'';return `<div class="cart-row"><img src="${p.images[0]||''}" alt=""><div><strong>${p.title}</strong><p>Tamanho ${x.size} · Qtd. ${x.qty}</p><p>${money(p.price)}</p></div><button class="remove" data-remove="${i}">Remover</button></div>`}).join('');$('#cartTotal').textContent=money(cartTotal());$$('[data-remove]').forEach(b=>b.onclick=()=>{cart.splice(Number(b.dataset.remove),1);persist();renderCart()})}
function renderFavorites(){const a=products.filter(p=>favs.has(p.slug));$('#favoriteItems').innerHTML=a.length?a.map(p=>`<div class="favorite-row"><img src="${p.images[0]||''}" alt=""><div><strong>${p.title}</strong><p>${money(p.price)}</p></div><button class="remove" data-unfav="${p.slug}">Remover</button></div>`).join(''):'<p class="checkout-note">Você ainda não favoritou nenhum produto.</p>';$$('[data-unfav]').forEach(b=>b.onclick=()=>toggleFav(b.dataset.unfav))}
function orderText(method){const lines=cart.map(x=>{const p=products.find(z=>z.slug===x.slug);return p?`• ${p.title} | Tam. ${x.size} | Qtd. ${x.qty} | ${money((p.price||0)*x.qty)}`:''}).filter(Boolean);return ['Olá! Quero finalizar meu pedido na JESUSFIRST.','',...lines,'',`Total: ${money(cartTotal())}`,`Forma de pagamento: ${method}`,'Entrega: Estados Unidos'].join('\n')}
function whatsappOrder(method){window.open('https://wa.me/15082154196?text='+encodeURIComponent(orderText(method)),'_blank')}
function renderCheckout(){const qty=cart.reduce((s,x)=>s+x.qty,0);$('#checkoutSummary').innerHTML=`<strong>${qty} item(ns)</strong><br>Total dos produtos: <strong>${money(cartTotal())}</strong><br>Entrega em qualquer lugar dos Estados Unidos<br>Sem pedido mínimo`;$('#paymentInstructions').hidden=true;$('#paymentInstructions').innerHTML=''}
function showPayment(type){const box=$('#paymentInstructions');box.hidden=false;if(type==='stripe')box.innerHTML='<strong>Cartão / Stripe</strong>O checkout seguro do Stripe será conectado antes da publicação final. Seu carrinho já está preparado para isso.';if(type==='zelle')box.innerHTML='<strong>Pagar com Zelle</strong>Envie o pagamento para <b>978 310-9700</b>. Depois, envie o pedido e o comprovante pelo WhatsApp.<br><button class="primary" id="sendWhatsZelle">ENVIAR PEDIDO NO WHATSAPP</button>';if(type==='venmo')box.innerHTML='<strong>Pagar com Venmo</strong>Envie para <b>@blckboston</b>. Depois, envie o pedido e o comprovante pelo WhatsApp.<br><button class="primary" id="sendWhatsVenmo">ENVIAR PEDIDO NO WHATSAPP</button>';const z=$('#sendWhatsZelle'),v=$('#sendWhatsVenmo');if(z)z.onclick=()=>whatsappOrder('Zelle');if(v)v.onclick=()=>whatsappOrder('Venmo')}
$$('.nav-link').forEach(b=>b.onclick=()=>setCategory(b.dataset.category));$('[data-route]').onclick=e=>{e.preventDefault();setCategory('lancamentos')};$('#searchForm').onsubmit=e=>{e.preventDefault();query=$('#searchInput').value.trim().toLowerCase();render()};$('#searchMobileBtn').onclick=()=>{const q=prompt('O que você procura?');if(q!==null){query=q.trim().toLowerCase();render()}};$('#sortSelect').onchange=e=>{sort=e.target.value;render()};$('#mobileMenuBtn').onclick=()=>$('#mainNav').classList.toggle('open');$('#cartBtn').onclick=()=>{renderCart();openDrawer($('#cartDrawer'))};$('#favoritesBtn').onclick=()=>{renderFavorites();openDrawer($('#favoritesDrawer'))};$$('[data-close]').forEach(b=>b.onclick=closeDrawers);$('#drawerBackdrop').onclick=closeDrawers;
$('#checkoutBtn').onclick=()=>{if(!cart.length)return alert('Sua sacola está vazia.');renderCheckout();closeDrawers();openDrawer($('#checkoutDrawer'))};$('#stripePay').onclick=()=>showPayment('stripe');$('#zellePay').onclick=()=>showPayment('zelle');$('#venmoPay').onclick=()=>showPayment('venmo');
updateBadges();render()})();