(()=>{
const products=window.JF_USA_PRODUCTS||[];
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
let category='all',query='',sort='featured',selected=null,selectedOption='';
const cart=JSON.parse(localStorage.getItem('jf-usa-cart')||'[]');
const money=n=>'$'+Number(n||0).toFixed(2);
const categories=[...new Set(products.map(p=>p.category).filter(Boolean))];

function persist(){localStorage.setItem('jf-usa-cart',JSON.stringify(cart));$('#cartCount').textContent=cart.reduce((a,x)=>a+x.qty,0)}
function filtered(){let a=products.filter(p=>category==='all'||p.category===category);if(query)a=a.filter(p=>(p.title+' '+(p.description||'')).toLowerCase().includes(query));if(sort==='az')a.sort((a,b)=>a.title.localeCompare(b.title));if(sort==='low')a.sort((a,b)=>a.price-b.price);if(sort==='high')a.sort((a,b)=>b.price-a.price);return a}
function renderCategories(){const box=$('#categoryNav');if(!categories.length){box.innerHTML='';return}box.innerHTML=['all',...categories].map(c=>`<button class="category-btn ${c===category?'active':''}" data-cat="${c}">${c==='all'?'SHOP ALL':c.toUpperCase()}</button>`).join('');$$('[data-cat]').forEach(b=>b.onclick=()=>{category=b.dataset.cat;render()})}
function render(){const a=filtered();$('#emptyState').style.display=a.length?'none':'block';$('#productGrid').innerHTML=a.map(p=>`<article class="product-card"><img src="${p.images?.[0]||''}" alt="${p.title}" data-open="${p.slug}"><h3 data-open="${p.slug}">${p.title}</h3><p>${money(p.price)}</p></article>`).join('');$$('[data-open]').forEach(x=>x.onclick=()=>openProduct(x.dataset.open));renderCategories()}
function openDrawer(el){$('#backdrop').hidden=false;el.classList.add('open');el.setAttribute('aria-hidden','false')}function close(){ $$('.drawer').forEach(d=>{d.classList.remove('open');d.setAttribute('aria-hidden','true')});$('#backdrop').hidden=true}
function openProduct(slug){selected=products.find(p=>p.slug===slug);if(!selected)return;const opts=selected.options||[];selectedOption=opts[0]||'';$('#productDetail').innerHTML=`<div class="detail"><img src="${selected.images?.[0]||''}" alt="${selected.title}"><div><p class="eyebrow">${(selected.category||'JESUSFIRST USA').toUpperCase()}</p><h2>${selected.title}</h2><p>${money(selected.price)}</p><p style="color:#666;line-height:1.7">${selected.description||''}</p>${opts.length?`<div class="option"><label>SELECT OPTION</label><div class="option-row">${opts.map((o,i)=>`<button class="option-btn ${i===0?'active':''}" data-option="${o}">${o}</button>`).join('')}</div></div>`:''}<button class="primary full" id="addBtn">ADD TO BAG</button></div></div>`;$$('[data-option]').forEach(b=>b.onclick=()=>{selectedOption=b.dataset.option;$$('[data-option]').forEach(x=>x.classList.toggle('active',x===b))});$('#addBtn').onclick=()=>addToCart();openDrawer($('#productDrawer'))}
function addToCart(){const f=cart.find(x=>x.slug===selected.slug&&x.option===selectedOption);f?f.qty++:cart.push({slug:selected.slug,option:selectedOption,qty:1});persist();renderCart();close();openDrawer($('#cartDrawer'))}
function subtotal(){return cart.reduce((s,x)=>{const p=products.find(z=>z.slug===x.slug);return s+(p?.price||0)*x.qty},0)}function shipping(){return subtotal()>=109.90?0:7}
function renderCart(){if(!cart.length){$('#cartItems').innerHTML='<p class="note">Your bag is empty.</p>';$('#cartTotal').textContent='$0.00';return}$('#cartItems').innerHTML=cart.map((x,i)=>{const p=products.find(z=>z.slug===x.slug);return p?`<div class="cart-row"><img src="${p.images?.[0]||''}" alt=""><div><strong>${p.title}</strong><p>${x.option||''} · Qty. ${x.qty}</p><span>${money(p.price*x.qty)}</span></div><button class="remove" data-rm="${i}">Remove</button></div>`:''}).join('');$('#cartTotal').textContent=money(subtotal()+shipping());$$('[data-rm]').forEach(b=>b.onclick=()=>{cart.splice(Number(b.dataset.rm),1);persist();renderCart()})}
async function checkout(){if(!cart.length)return alert('Your bag is empty.');const btn=$('#checkoutBtn'),old=btn.textContent;btn.disabled=true;btn.textContent='OPENING STRIPE…';try{const items=cart.map(x=>({slug:x.slug,size:x.option||'',lang:'en',qty:x.qty}));const res=await fetch('https://tjeiyvgyhngztgnxtjaq.supabase.co/functions/v1/jesusfirst-create-checkout',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({store:'usa',items})});const data=await res.json();if(!res.ok||!data.url)throw new Error(data.error||'Checkout is unavailable.');location.href=data.url}catch(e){alert(e.message);btn.disabled=false;btn.textContent=old}}

$('#searchInput').oninput=e=>{query=e.target.value.trim().toLowerCase();render()};$('#sortSelect').onchange=e=>{sort=e.target.value;render()};$('#cartBtn').onclick=()=>{renderCart();openDrawer($('#cartDrawer'))};$('#checkoutBtn').onclick=checkout;$$('[data-close]').forEach(b=>b.onclick=close);$('#backdrop').onclick=close;persist();render();
})();